#ifndef __CONFIGURATION_H__
#define __CONFIGURATION_H__

#define GAME_FPS 60.f
#define GAME_WIDTH 480.f
#define GAME_HEIGHT 800.f
#define GAME_COLOUR 0x4E, 0xC0, 0xCA, 0xFF // RGBA
#define GAME_SCROLL_SPEED 3.f
#define GAME_PHYSICS_SPEED 4.f
#define GAME_PHYSICS_GRAVITY 0, -80.f // Vec2

#define FONT_SIZE_SCORE 56

#define PLAYER_ANIMATION_SPEED 12.f
#define PLAYER_JUMP_HEIGHT 20.f
#define PLAYER_JUMP_VELOCITY 0, 80.f // Vec2

#define OBSTACLE_GAP 120.f
#define OBSTACLE_PADDING 160.f
#define OBSTACLE_FREQUENCY_TIME 1500

enum Layer
{
    BG_STATIC_LAYER,
    BG_SCROLL_LAYER,
    OBSTACLE_LAYER,
    PLAYER_LAYER,
    SCORE_LAYER,
};

#endif // __CONFIGURATION_H__
